# Generated by Django 4.2 on 2023-08-17 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('synopsis', models.TextField()),
                ('poster', models.ImageField(upload_to='posters/')),
                ('infotrailer', models.FileField(upload_to='info-trailers/')),
                ('theater', models.CharField(choices=[('Alliance Francaise', 'Alliance Francaise'), ('Kenya National Theater', 'Kenya National Theater'), ('Nairobi Cinemas', 'Nairobi Cinema')], max_length=255)),
                ('is_available', models.BooleanField(default=False)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('synopsis', models.TextField()),
                ('video', models.FileField(upload_to='videos/')),
                ('trailer', models.FileField(upload_to='trailers/')),
                ('video_poster', models.ImageField(upload_to='video_poster/')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ViewHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heartstringApp.video')),
            ],
        ),
        migrations.CreateModel(
            name='VideoStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.CharField(choices=[('SD', 'Standard Definition'), ('HD', 'High Definition'), ('FHD', 'Full HD'), ('4K', '4K Ultra HD')], max_length=50)),
                ('is_default', models.BooleanField(default=False)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heartstringApp.video')),
            ],
        ),
        migrations.CreateModel(
            name='VideoPayment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_id', models.CharField(max_length=50)),
                ('amount', models.CharField(max_length=100)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heartstringApp.video')),
            ],
        ),
        migrations.CreateModel(
            name='VideoCast',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='cast-pictures/')),
                ('real_name', models.CharField(max_length=255)),
                ('cast_name', models.CharField(max_length=255)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('video_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heartstringApp.video')),
            ],
        ),
        migrations.CreateModel(
            name='VideoAvailability',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('three_days', models.CharField(max_length=100)),
                ('three_price', models.CharField(max_length=100)),
                ('seven_days', models.CharField(max_length=100)),
                ('seven_price', models.CharField(max_length=100)),
                ('fourteen_days', models.CharField(max_length=100)),
                ('fourteen_price', models.CharField(max_length=100)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('video_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heartstringApp.video')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('seat_numbers', models.CharField(max_length=100)),
                ('ticket_type', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('email', models.EmailField(max_length=254)),
                ('qr_code', models.ImageField(upload_to='qr_codes/')),
                ('purchased', models.BooleanField(default=False)),
                ('payment_id', models.CharField(blank=True, max_length=50, null=True)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('play', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='heartstringApp.play')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlayTime',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('play_date', models.DateField()),
                ('time1', models.CharField(default=None, max_length=255)),
                ('time2', models.CharField(default=None, max_length=255)),
                ('time3', models.CharField(default=None, max_length=255)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('play_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heartstringApp.play')),
            ],
        ),
        migrations.CreateModel(
            name='PlayCast',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='play-cast-pictures/')),
                ('real_name', models.CharField(max_length=255)),
                ('cast_name', models.CharField(max_length=255)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('play_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heartstringApp.play')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_id', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heartstringApp.ticket')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OtherOffers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('offers_name', models.CharField(max_length=225)),
                ('offer_day', models.DateField(null=True)),
                ('promo_code', models.CharField(max_length=100)),
                ('percentage', models.CharField(max_length=100)),
                ('number_of_tickets', models.CharField(max_length=100)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('play_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heartstringApp.play')),
            ],
        ),
        migrations.CreateModel(
            name='Bogof',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bogof', models.BooleanField(default=False)),
                ('offer_day', models.DateField(null=True)),
                ('number_of_tickets', models.CharField(max_length=100)),
                ('promo_code', models.CharField(max_length=100)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('play_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heartstringApp.play')),
            ],
        ),
    ]
