# Generated by Django 4.2 on 2023-08-21 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heartstringApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play',
            name='theater',
            field=models.CharField(choices=[('Alliance Francaise', 'Alliance Francaise'), ('Kenya National Theater', 'Kenya National Theater'), ('Nairobi Cinemas', 'Nairobi Cinemas')], max_length=255),
        ),
    ]
