# Generated by Django 4.2 on 2023-08-21 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heartstringApp', '0002_alter_play_theater'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='user_type',
            field=models.CharField(default='normal', max_length=20),
        ),
    ]
