# Generated by Django 4.2 on 2023-09-08 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heartstringApp', '0003_useraccount_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_id',
        ),
    ]
