# Generated by Django 4.2 on 2024-02-01 09:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('heartstringApp', '0004_video_duration_alter_ticket_ticket_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='play',
            name='amount',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='play',
            name='location',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_number',
            field=models.CharField(default='8FBF23A13F', max_length=10, unique=True),
        ),
    ]
