# Generated by Django 4.2 on 2023-09-08 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heartstringApp', '0004_remove_payment_payment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='payment_id',
        ),
    ]
