# Generated by Django 4.2 on 2024-02-02 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heartstringApp', '0005_play_amount_play_location_alter_ticket_ticket_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('seat_id', models.CharField(max_length=10, unique=True)),
                ('row', models.CharField(max_length=1)),
                ('column', models.PositiveIntegerField()),
                ('wing', models.CharField(max_length=10)),
                ('status', models.BooleanField(default=False)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_number',
            field=models.CharField(default='3B945C6413', max_length=10, unique=True),
        ),
    ]
