# Generated by Django 4.2 on 2023-09-08 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heartstringApp', '0005_remove_ticket_payment_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='play',
            new_name='play_id',
        ),
    ]
