# Generated by Django 4.2 on 2024-02-06 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heartstringApp', '0006_seat_alter_ticket_ticket_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='play',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='play',
            name='location',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_number',
            field=models.CharField(default='3964D5541A', max_length=10, unique=True),
        ),
    ]
