# Generated by Django 4.2 on 2023-09-08 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heartstringApp', '0006_rename_play_ticket_play_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_number',
            field=models.CharField(default='DA7FEAAC0B', max_length=10, unique=True),
        ),
    ]
