# Generated by Django 4.2 on 2024-02-07 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heartstringApp', '0007_remove_play_amount_remove_play_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='play',
            name='amount',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='play',
            name='location',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_number',
            field=models.CharField(default='5B26ED3C35', max_length=10, unique=True),
        ),
    ]
