# Generated by Django 4.2 on 2024-02-09 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heartstringApp', '0008_play_amount_play_location_alter_ticket_ticket_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play',
            name='location',
            field=models.CharField(max_length=25655),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_number',
            field=models.CharField(default='188660BD44', max_length=10, unique=True),
        ),
    ]
