# Generated by Django 4.2 on 2024-03-04 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heartstringApp', '0014_alter_payment_ticket_alter_payment_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='play_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='play_time',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_number',
            field=models.CharField(default='4D12523E14', max_length=10, unique=True),
        ),
    ]
